artifact_location: /home/opoloholtz_amaris/Repos/marvelous-databricks-course-OpoloHOLTZ/scripts/databrics/539253455096887722
creation_time: 1740758527096
experiment_id: '539253455096887722'
last_update_time: 1740758527096
lifecycle_stage: active
name: /Shared/default-ccc-basic
