aliases: []
creation_timestamp: 1740758551330
current_stage: None
description: null
last_updated_timestamp: 1740758551330
name: maven_training_databricks.default_ccc.default_ccc_model_basic
run_id: 0d01d1c5dc7649acaf2114e53297e7c1
run_link: null
source: /home/opoloholtz_amaris/Repos/marvelous-databricks-course-OpoloHOLTZ/scripts/databrics/539253455096887722/0d01d1c5dc7649acaf2114e53297e7c1/artifacts/logit_pipeline_model
status: READY
status_message: null
storage_location: /home/opoloholtz_amaris/Repos/marvelous-databricks-course-OpoloHOLTZ/scripts/databrics/539253455096887722/0d01d1c5dc7649acaf2114e53297e7c1/artifacts/logit_pipeline_model
user_id: null
version: 1
