artifact_location: /home/opoloholtz_amaris/Repos/marvelous-databricks-course-OpoloHOLTZ/scripts/databrics/0
creation_time: 1740758390359
experiment_id: '0'
last_update_time: 1740758390359
lifecycle_stage: active
name: Default
