digest: eff7c5e9
name: dataset
profile: 'null'
schema: '{"mlflow_colspec": [{"type": "string", "name": "AGE", "required": true},
  {"type": "integer", "name": "SEX", "required": true}, {"type": "integer", "name":
  "EDUCATION", "required": true}, {"type": "integer", "name": "MARRIAGE", "required":
  true}, {"type": "integer", "name": "PAY_0", "required": true}, {"type": "integer",
  "name": "PAY_2", "required": true}, {"type": "integer", "name": "PAY_3", "required":
  true}, {"type": "integer", "name": "PAY_4", "required": true}, {"type": "integer",
  "name": "PAY_5", "required": true}, {"type": "integer", "name": "PAY_6", "required":
  true}, {"type": "integer", "name": "LIMIT_BAL", "required": true}, {"type": "integer",
  "name": "BILL_AMT1", "required": true}, {"type": "integer", "name": "BILL_AMT2",
  "required": true}, {"type": "integer", "name": "BILL_AMT3", "required": true}, {"type":
  "integer", "name": "BILL_AMT4", "required": true}, {"type": "integer", "name": "BILL_AMT5",
  "required": true}, {"type": "integer", "name": "BILL_AMT6", "required": true}, {"type":
  "integer", "name": "PAY_AMT1", "required": true}, {"type": "integer", "name": "PAY_AMT2",
  "required": true}, {"type": "integer", "name": "PAY_AMT3", "required": true}, {"type":
  "integer", "name": "PAY_AMT4", "required": true}, {"type": "integer", "name": "PAY_AMT5",
  "required": true}, {"type": "integer", "name": "PAY_AMT6", "required": true}, {"type":
  "integer", "name": "default_payment_next_month", "required": true}, {"type": "string",
  "name": "ID", "required": true}, {"type": "datetime", "name": "update_timestamp_utc",
  "required": true}]}'
source: '{"delta_table_name": "maven_training_databricks.default_ccc.train_set", "delta_table_version":
  "0", "is_databricks_uc_table": true, "delta_table_id": null}'
source_type: delta_table
